name: .NET Core Desktop CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: |
        cd CyberSecurityChatBot-Part2
        dotnet restore CyberSecurityChatBot-Part2.csproj

    - name: Build the application
      run: |
        cd CyberSecurityChatBot-Part2
        dotnet build CyberSecurityChatBot-Part2.csproj --configuration Release --no-restore
